
[project]
name = "catamaran-btc"
description = ''
authors = ["friedger"]
telemetry = false

requirements = [
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v5" },
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-helper" },
    { contract_id = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token" },
]

[contracts.bitcoin-helper-wtx-v1]
path = "contracts/clarity-bitcoin-helper-wtx.clar"
depends_on = []
epoch = "3.0"
clarity = 3


[contracts.btc-sbtc-swap]
path = "contracts/btc-sbtc-swap.clar"
depends_on = []
epoch = "3.0"
clarity = 3


[repl.remote_data]
enabled = false
api_url = "https://api.hiro.so"
initial_height = 595012
[notebooks]
